# Generated by Django 3.0.1 on 2019-12-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
    ]
