# Generated by Django 3.0.1 on 2019-12-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20191228_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date',
            new_name='created_at',
        ),
    ]
